create table if not exists public.match_events (
  id bigint generated by default as identity primary key,
  match_id bigint not null references public.matches(id) on delete cascade,
  club_id bigint not null references public.clubs(id) on delete cascade,
  sequence integer not null check (sequence > 0),
  quarter smallint not null check (quarter between 1 and 4),
  team text not null check (team in ('own', 'opponent')),
  category text not null check (category in ('goal', 'shot', 'foul', 'action', 'goalkeeper', 'penalty', 'system')),
  stat_key text not null check (length(trim(stat_key)) > 0),
  delta integer not null check (delta <> 0),
  value_after integer not null check (value_after >= 0),
  player_id bigint references public.players(id) on delete set null,
  goalkeeper_player_id bigint references public.players(id) on delete set null,
  label text,
  metadata jsonb not null default '{}'::jsonb,
  occurred_at timestamptz not null default now(),
  is_undone boolean not null default false,
  unique (match_id, sequence)
);

create index if not exists match_events_match_sequence_idx on public.match_events (match_id, sequence);
create index if not exists match_events_match_quarter_idx on public.match_events (match_id, quarter);
create index if not exists match_events_player_idx on public.match_events (player_id);
create index if not exists match_events_goalkeeper_idx on public.match_events (goalkeeper_player_id);

alter table public.match_events enable row level security;

drop policy if exists match_events_select on public.match_events;
drop policy if exists match_events_insert on public.match_events;
drop policy if exists match_events_update on public.match_events;

create policy match_events_select on public.match_events for select to authenticated
using (
  exists (
    select 1 from public.profiles p
    where p.id = (select auth.uid())
      and (p.is_super_admin or p.club_id = match_events.club_id)
      and p.role in ('admin', 'coach', 'viewer')
  )
);

create policy match_events_insert on public.match_events for insert to authenticated
with check (
  exists (
    select 1 from public.profiles p
    where p.id = (select auth.uid())
      and (p.is_super_admin or p.club_id = match_events.club_id)
      and p.role in ('admin', 'coach')
  )
  and exists (select 1 from public.matches m where m.id = match_events.match_id and m.club_id = match_events.club_id)
  and (player_id is null or exists (select 1 from public.players pl where pl.id = match_events.player_id and pl.club_id = match_events.club_id))
  and (goalkeeper_player_id is null or exists (select 1 from public.players gk where gk.id = match_events.goalkeeper_player_id and gk.club_id = match_events.club_id))
);

create policy match_events_update on public.match_events for update to authenticated
using (
  exists (
    select 1 from public.profiles p
    where p.id = (select auth.uid())
      and (p.is_super_admin or p.club_id = match_events.club_id)
      and p.role in ('admin', 'coach')
  )
)
with check (is_undone = true);
