-- Ordered match actions grouped by period.
-- Safe to run after matches, players and profiles already exist.
CREATE TABLE IF NOT EXISTS public.match_actions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id UUID NOT NULL DEFAULT gen_random_uuid(),
  match_id INTEGER NOT NULL REFERENCES public.matches(id) ON DELETE CASCADE,
  player_id INTEGER NOT NULL REFERENCES public.players(id) ON DELETE RESTRICT,
  quarter SMALLINT NOT NULL CHECK (quarter BETWEEN 1 AND 4),
  sequence INTEGER NOT NULL CHECK (sequence >= 1),
  action_key TEXT NOT NULL CHECK (length(trim(action_key)) > 0),
  created_by UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT match_actions_client_id_key UNIQUE (client_id),
  CONSTRAINT match_actions_match_sequence_key UNIQUE (match_id, sequence)
);

CREATE INDEX IF NOT EXISTS idx_match_actions_match_quarter_sequence
  ON public.match_actions (match_id, quarter, sequence);

CREATE INDEX IF NOT EXISTS idx_match_actions_player_id
  ON public.match_actions (player_id);

ALTER TABLE public.match_actions ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'match_actions'
      AND policyname = 'match_actions_select_by_club'
  ) THEN
    CREATE POLICY match_actions_select_by_club
      ON public.match_actions FOR SELECT
      USING (
        EXISTS (
          SELECT 1
          FROM public.matches m
          JOIN public.profiles p ON p.club_id = m.club_id
          WHERE m.id = match_actions.match_id
            AND p.id = auth.uid()
        )
        OR EXISTS (
          SELECT 1 FROM public.profiles p
          WHERE p.id = auth.uid() AND p.is_super_admin = TRUE
        )
      );
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'match_actions'
      AND policyname = 'match_actions_insert_by_club'
  ) THEN
    CREATE POLICY match_actions_insert_by_club
      ON public.match_actions FOR INSERT
      WITH CHECK (
        match_id IN (
          SELECT m.id
          FROM public.matches m
          WHERE m.club_id IN (
            SELECT p.club_id
            FROM public.profiles p
            WHERE p.id = auth.uid()
              AND p.role IN ('admin', 'coach')
          )
        )
      );
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'match_actions'
      AND policyname = 'match_actions_update_by_club'
  ) THEN
    CREATE POLICY match_actions_update_by_club
      ON public.match_actions FOR UPDATE
      USING (
        match_id IN (
          SELECT m.id
          FROM public.matches m
          WHERE m.club_id IN (
            SELECT p.club_id
            FROM public.profiles p
            WHERE p.id = auth.uid()
              AND p.role IN ('admin', 'coach')
          )
        )
      )
      WITH CHECK (
        match_id IN (
          SELECT m.id
          FROM public.matches m
          WHERE m.club_id IN (
            SELECT p.club_id
            FROM public.profiles p
            WHERE p.id = auth.uid()
              AND p.role IN ('admin', 'coach')
          )
        )
      );
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'match_actions'
      AND policyname = 'match_actions_delete_by_club'
  ) THEN
    CREATE POLICY match_actions_delete_by_club
      ON public.match_actions FOR DELETE
      USING (
        match_id IN (
          SELECT m.id
          FROM public.matches m
          WHERE m.club_id IN (
            SELECT p.club_id
            FROM public.profiles p
            WHERE p.id = auth.uid()
              AND p.role IN ('admin', 'coach')
          )
        )
      );
  END IF;
END
$$;
